### PR TITLE
IR v3.10.1: More thrift 0.13.0 preparation

### PR DESCRIPTION
**Pull request by natewoods-wf**
### Story:
We missed a few of the changes required when preparing for our customers to move to thrift 0.13.0.
This PR is from an integration branch, into a "hotfix" branch, that will be cut+released as v3.10.1.
This is a version we can have teams upgrade to w/o needing to upgrade to thrift 0.13.0 immediately.

Independent PRs into the integration branch:
* https://github.com/Workiva/frugal/pull/1360 - Patching Java extended servers
* https://github.com/Workiva/frugal/pull/1359 - Fixing some local integration testing
* https://github.com/Workiva/frugal/pull/1352 - Preparing Go/pherjs for thfirt 0.13.0
* https://github.com/Workiva/frugal/pull/1365 - Manual version update for IR (immediate release)

### Acceptance Criteria:
- [x] At least one ServicePlatform member has reviewed and +1'd
- [x] Code has been tested and results documented
- [x] Unit tests have been updated
- [x] Updates to documentation if necessary
- [x] Verify and document changes to any other Messaging components
- ~~Pull request made against the 'develop' branch, not master~~ (IR)

### Design Notes:
Need to encapsulate changing logic in thrift so we maintain backwards compatibility with generated code.  General process for developing this involves:
1. branching off of frugal master
2. updating everything to thrift 0.13.0
3. hand fix whatever is broken (tests/examples/etc) (example: go https://github.com/Workiva/frugal/pull/1350)
4. take note of all breaking changes in generated code needed
5. refactor generated logic to use library functions where breaking changes were needed
6. backport that refactor to be thrift 0.10.0 and 0.9.3 compatible (library side)
7. update the generator based on the v3.10.x branch
8. make a PR to our integration branch v3.10.0-1-dev
9. Add tests and SDLC things
10. then you get merged here.

If you get to step 4 and generated code doesn't need to be fixed, make a PR to `develop` with your changes, as the next release on develop will be v3.11.x, which is targeting the "includes transition to v0.13.0" changes

*UPDATE: the required dart and [python](https://github.com/Workiva/frugal/pull/1351) changes to move to thrift 0.13.0 **DO NOT** require generated code changes, and have their changes targeting `develop` for the next release (v3.11.1)*

### How To Test:
Wire this branch through our dependency web into "our most advanced internal consumers" (names are censored), and ensure successful CI and automated integration testing.

### My Test Results:
Success! (see References in this "conversation"; hidden to non-Workiva members :cry:)

#### Reviewers:
@Workiva/service-platform

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by natewoods-wf** [comment]
+1 @ryanwilson-wk's tango with SNAPSHOT for testing purposes

**Review by charliekump-wf — APPROVED** [review]
+1

**Review by ryanwilson-wk — APPROVED** [review]

**Comment by natewoods-wf** [comment]
+10 @Workiva/release-management-p for IR

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
