### PR TITLE
INFENG-5441 Release 2.17.0

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/INFENG-5441

@Workiva/messaging-pp

* #986 add java FServlet to cross tests; minor refactor
* #985 Support deprecated annotation for fields
* #977 Fix vendor folder. Use glide, but keep godep around for people using godep commands

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Module Findings
No security relevant content detected. Please review for security relevance and request security review as needed.

**Comment by brianshannan-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
@Workiva/product2

**Comment by keatoncarter-wf** [comment]
+1 lgtm

**Pull request merged**
