### PR TITLE
MEX-843 Release v3.16.16

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/MEX-843

@Workiva/product2

* #2143 Pin mockito 5
* #2144 go-tool: bump golang.org/x/tools from 0.6.0 to 0.7.0
* #2147 py-lib: bump coverage from 7.2.1 to 7.2.2 in /lib/python
* #2146 java-lib: bump netty-all from 4.1.89.Final to 4.1.90.Final in /lib/java
* #2148 java-lib: bump jnats from 2.16.8 to 2.16.9 in /lib/java
* #2149 Consume messaging-docker-images 0.1.14
* #2151 go-test: bump github.com/nats-io/nats.go from 1.24.0 to 1.25.0 in /test/integration
* #2152 go-exam: bump github.com/nats-io/nats.go from 1.24.0 to 1.25.0 in /examples/go
* #2150 go-lib: bump github.com/nats-io/nats.go from 1.24.0 to 1.25.0 in /lib/go
* #2153 Prepare for dart_dev v4.0.0
* #2156 w_common v3 rollout - 1 of 2 raise max

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by toddbeckman-wf — APPROVED** [review]

**Comment by toddbeckman-wf** [comment]
QA +1 CI passes

**Comment by toddbeckman-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
