### PR TITLE
Fix vendor folder. Use glide, but keep godep around for people using godep commands

### PR DESCRIPTION
**Pull request by charliestrawn-wf**

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Module Findings
No security relevant content detected. Please review for security relevance and request security review as needed.

**Comment by brianshannan-wf** [comment]
@Workiva/messaging-pp @Workiva/infre-product

**Comment by charliestrawn** [comment]
+1

**Comment by garrickpeterson-wf** [comment]
This is a huge diff, but it looks like we are still checking in the dependencies? I thought the entire premise of using glide was not having to check them in to get consistent builds.

Speaking only from an infre point of view - when we have glide dependencies, we do not check the vendor directory into git.

**Comment by brianshannan-wf** [comment]
Note: please don't review until I'm able to test all the godep commands still work properly

**Comment by brianshannan-wf** [comment]
We need to keep the vendor folder for now due to godep. We can remove this once the deprecation period is over, which we need to decide on and communicate out

**Comment by garrickpeterson-wf** [comment]
+1

**Comment by tylerrinnan-wf** [comment]
+1

**Pull request merged**
