### PR TITLE
SPLAT-1570 Release v3.14.8

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/SPLAT-1570

@Workiva/product2

* #1628 Widen Dependency Ranges Blocking Dart 2.13
* #1638 java-lib: bump jmh.version from 1.32 to 1.33 in /lib/java
* #1635 SPLAT-1292 - Handle service unavailable for nats and http transports (GO)
* #1642 java-test: bump netty-all from 4.1.66.Final to 4.1.67.Final in /test/integration/java/frugal-integration-test
* #1644 java-exam: bump netty-all from 4.1.66.Final to 4.1.67.Final in /examples/java
* #1643 java-lib: bump netty-all from 4.1.66.Final to 4.1.67.Final in /lib/java
* #1650 java-exam: bump activemq-client from 5.16.2 to 5.16.3 in /examples/java
* #1645 java-test: bump gson from 2.8.7 to 2.8.8 in /test/integration/java/frugal-integration-test
* #1646 java-test: bump activemq-client from 5.16.2 to 5.16.3 in /test/integration/java/frugal-integration-test
* #1648 java-lib: bump gson from 2.8.7 to 2.8.8 in /lib/java
* #1647 java-lib: bump mockito-core from 3.11.2 to 3.12.1 in /lib/java
* #1652 java-test: bump jnats from 2.11.5 to 2.11.6 in /test/integration/java/frugal-integration-test
* #1654 java-lib: bump mockito-core from 3.12.1 to 3.12.4 in /lib/java
* #1653 java-lib: bump jnats from 2.11.5 to 2.11.6 in /lib/java
* #1655 go-test: bump github.com/nats-io/nats.go from 1.11.0 to 1.12.0 in /test/integration
* #1657 go-exam: bump github.com/nats-io/nats.go from 1.11.0 to 1.12.0 in /examples/go
* #1656 go-lib: bump github.com/nats-io/nats.go from 1.11.0 to 1.12.0 in /lib/go
* #1658 go-lib: bump github.com/nats-io/nats-server/v2 from 2.2.6 to 2.4.0 in /lib/go
* #1637 SPLAT-1292 - Handle empty messages and http exceptions (Python)
* #1659 Give consumers the option to omit server generation for a parsed service (in golang generation)
* #1660 Export a few functions from the `compile` package

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>lib/java/pom.xml</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by charliekump-wf — APPROVED** [review]
+1

**Comment by charliekump-wf** [comment]
@Workiva/release-management-p ready for merge.

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
