### PR TITLE
dart: Add dartdoc reference for enum field type

### PR DESCRIPTION
**Pull request by brettkail-wk**
### Story:
The expected enum type for fields is not easily discoverable in generated Dart code.  Add a dartdoc reference to the enum type.

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by yuanmwang-wf** [comment]
@brettkail-wk Could you update the target branch to `develop` instead of master? Workiva build is currently failing because of it.

**Comment by brettkail-wk** [comment]
@yuanmwang-wf Ugh, of course.  I carefully rebased onto wk/develop, but then I mis-opened the PR, sorry.

**Comment by brettkail-wk** [comment]
Opened #1169.

**Pull request closed without merging**
