### PR TITLE
INFENG-5816 Release 2.20.0

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/INFENG-5816

@Workiva/messaging-pp

* #1005 java: Include cause in HTTP TTransportException
* #1007 INFENG-5834: Allow loose pinning of minor versions of requests and six
* #1008 Workiva-Build: Update Dockerfile to mirror smithy.yaml
* #1006 DS_Artifactory_Updates
* #1010 INFENG-5814 add struct name to required field error
* #1013 java: Include cause for HTTP timeout exception
* #1011 INFENG-5798: Add Dockerfile for building a frugal image

### CODE REVIEW

**Comment by brianshannan-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
@Workiva/product2

**Comment by charliestrawn-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
@aviary-wf

**Comment by brianshannan-wf** [comment]
@aviary-wf

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
