### PR TITLE
Resolving ambiguous Thrift import

### PR DESCRIPTION
**Pull request by natewoods-wf**
### Story:
With our recent move to go modules, and the current structure of this repository, the root `go.mod` is picking up apache/thrift as a dependency, when it shouldn't.  This effort moves the "gold file" tests into a `testdata` directory, which is ignored by the go build system.  This ensures that the generated gold files don't improperly influence the root `go.mod`s dependency list.  Additionally, by adding more than one `go.mod` file to the repo, we can guard against the dependency propagation.  The specific modifications are delineated in the list below.

* Move generated tests into the `testdata` directory
* Add a "blocking" `go.mod` file to the `examples/go` directory
* Moving `test/*.go` to `compiler/*` to match standard go testing practices (tests alongside subject code)
* Update examples to be modules focused
  * Removed `examples/go/glide.yaml`
  * Added `examples/go/go.mod` with the appropriate `replace` directive for frugal/lib/go
  * Updated makefile to build all the binaries (no symlinking needed with `replace` directive in go.mod
* Removed the propagated imports from `go.mod` (via `go mod tidy` once everything else was managed)
* Updated `scripts/update.py` to generate with new process

With our latest release, our automated update script was [creating these changes automatically](https://github.com/Workiva/frugal/commit/4ca7d80399ef373e8f273582bda77504e04bbe06#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6).  This was a conflicting thrift version with our targeted 0.14.0.  This comes from the fact that thrift added and [then removed a go.mod](https://github.com/apache/thrift/pull/2311) from it's lib/go/thrift directory.   The thrift maintainers will eventually add a go.mod back, and it's actively being discussed on [upcoming go changes](https://github.com/golang/go/issues/34055#issuecomment-763880343).  All this caused our consumers to run into the following issue when folks were consuming frugal v3.14.0

```
github.com/Workiva/<internal-repo> imports
        github.com/apache/thrift/lib/go/thrift: ambiguous import: found package github.com/apache/thrift/lib/go/thrift in multiple modules:
        github.com/apache/thrift v0.14.0 (~/go/pkg/mod/github.com/apache/thrift@v0.14.0/lib/go/thrift)
        github.com/apache/thrift/lib/go/thrift v0.0.0-20210120171102-e27e82c46ba4 (~/go/pkg/mod/github.com/apache/thrift/lib/go/thrift@v0.0.0-20210120171102-e27e82c46ba4)
```

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
After reviewing the tests in `test/*.go`, they are all compiler tests using generated gold files.  Following standards put forth in the past few years in the go world, it would follow that the generated assets should be stored in a `testdata` directory (which the go compiler will ignore).

### How To Test:
```sh
go test ./...
go mod tidy
git status
```

### My Test Results:
```sh
$ go test ./...
?       github.com/Workiva/frugal       [no test files]
ok      github.com/Workiva/frugal/compiler      1.851s
?       github.com/Workiva/frugal/compiler/generator    [no test files]
?       github.com/Workiva/frugal/compiler/generator/dartlang   [no test files]
?       github.com/Workiva/frugal/compiler/generator/golang     [no test files]
?       github.com/Workiva/frugal/compiler/generator/html       [no test files]
?       github.com/Workiva/frugal/compiler/generator/java       [no test files]
?       github.com/Workiva/frugal/compiler/generator/json       [no test files]
?       github.com/Workiva/frugal/compiler/generator/python     [no test files]
?       github.com/Workiva/frugal/compiler/globals      [no test files]
?       github.com/Workiva/frugal/compiler/parser       [no test files]
?       github.com/Workiva/frugal/scripts/skynet/cross  [no test files]
?       github.com/Workiva/frugal/scripts/smithy        [no test files]
$ go mod tidy
$ git status
On branch conflicting-thrift
Your branch is up to date with 'origin/conflicting-thrift'.

nothing to commit, working tree clean
$
```

I also used a `replace` statement in an internal repo to pin this dependency and successfully resolved the ambiguous import.

```sh
# Before replace line
$ grep 'thrift\|frugal' go.mod
        github.com/Workiva/frugal v3.14.0+incompatible
        github.com/Workiva/frugal/lib/go v0.0.0-20210309201517-23c713d4d9f4
        github.com/apache/thrift v0.14.0
$ go mod tidy -v
github.com/Workiva/<internal-repository> imports
        github.com/apache/thrift/lib/go/thrift: ambiguous import: found package github.com/apache/thrift/lib/go/thrift in multiple modules:
        github.com/apache/thrift v0.14.0 (~/go/pkg/mod/github.com/apache/thrift@v0.14.0/lib/go/thrift)
        github.com/apache/thrift/lib/go/thrift v0.0.0-20210120171102-e27e82c46ba4 (~/go/pkg/mod/github.com/apache/thrift/lib/go/thrift@v0.0.0-20210120171102-e27e82c46ba4)

# After replace line (pointing to a this version of frugal checked out)
$ grep 'thrift\|frugal' go.mod
        github.com/Workiva/frugal v3.14.0+incompatible
        github.com/Workiva/frugal/lib/go v0.0.0-20210309201517-23c713d4d9f4
        github.com/apache/thrift v0.14.0
replace github.com/Workiva/frugal => ../frugal
$ go mod tidy -v
$
```

#### Reviewers:
@Workiva/service-platform

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
<details>
<summary>(1) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by charliekump-wf** [comment]
+10 and tested update script changes here https://github.com/Workiva/frugal/pull/1504

**Review by charliekump-wf — APPROVED** [review]

**Comment by natewoods-wf** [comment]
@Workiva/release-management-p for merge

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
