### PR TITLE
dart: Use const for simple constants

### PR DESCRIPTION
**Pull request by brettkail-wk**
### Story:
[INFENG-7871](https://jira.atl.workiva.net/browse/INFENG-7871)

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [x] Code has been tested and results documented
- [x] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [x] Pull request made against the 'develop' branch, not master

### Design Notes:
In theory, it should be possible to resolve indirect constants, but there is currently no infrastructure for resolving indirect constants linearly (and without infinite loops), so the PR skips those scenarios for now.

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
+1

**Comment by blakeroberts-wk** [comment]
+1

**Comment by yuanmwang-wf** [comment]
+1

**Pull request merged**
