### PR TITLE
dart scopes should import Uint8List similar to services

### PR DESCRIPTION
**Pull request by brianshannan-wf**
@Workiva/messaging-pp

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by markerickson-wf** [comment]
+1

**Comment by matthinrichsen-wf** [comment]
+1

**Comment by charliestrawn-wf** [comment]
+1

**Comment by markcampanelli-wf** [comment]
I have not been able to verify that this import is fixed in https://github.com/Workiva/skaardb/blob/master/dart-bindings/lib/src/frugal_gen/doc_plat_frugal/f_dp_events_scope.dart#L5

I have a priority issue to address before trying to verify this better. (May be a godep issue preventing the proper frugal version.)

**Comment by markcampanelli-wf** [comment]
Verified that this fixes Dart import in https://github.com/Workiva/skaardb/blob/master/dart-bindings/lib/src/frugal_gen/doc_plat_frugal/f_dp_events_scope.dart#L5.

**Pull request merged**
