### PR TITLE
SPLAT-198: Update develop

### PR DESCRIPTION
**Pull request by natewoods-wf**
# [SPLAT-198](https://jira.atl.workiva.net/browse/SPLAT-198)
Issue Status

### Story:
Merge hotfix back into development branches

### Acceptance Criteria:
- [ ] At least one Service Platform member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
v3.11.1 was released with a hotfix, need to merge those changes back into develop

### How To Test:
CI

### My Test Results:
🟡 

#### Reviewers:
@Workiva/service-platform

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by charliekump-wf — APPROVED** [review]
+1

**Comment by natewoods-wf** [comment]
@Workiva/release-management-p for merge into develop

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
