### PR TITLE
Java: Point to artifactory pro

### PR DESCRIPTION
**Pull request by stevenosborne-wf**
### Story:
Move all references to artifactory pro

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
legacy artifactory is dead, long live artifactory pro

### How To Test:
Integration tests pass. Example works properly.

### My Test Results:
👍 

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by yuanmwang-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
