### PR TITLE
don't show dependencies multiple times in the html index

### PR DESCRIPTION
**Pull request by brianshannan-wf**
If a dependency was included multiple times via a transitive dependency, like `b` depends on `a` and `c` depends on both `b` and `a`, then `a` shouldn't be shown multiple times in the index generated by the html generator.

@Workiva/messaging-pp @markcampanelli-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by brianshannan-wf** [comment]
travis is currently failing for an unrelated problem

**Comment by charliestrawn-wf** [comment]
+1

**Comment by tylerrinnan-wf** [comment]
lgtm

**Pull request merged**
