### PR TITLE
MEX-1975 Release v3.17.10

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/MEX-1975

@Workiva/product2

* #2421 java-lib: bump org.apache.maven.plugins:maven-gpg-plugin from 3.1.0 to 3.2.0 in /lib/java
* #2420 go-tool: bump golang.org/x/tools from 0.18.0 to 0.19.0
* #2423 java-lib: bump org.apache.maven.plugins:maven-gpg-plugin from 3.2.0 to 3.2.1 in /lib/java
* #2424 go-lib: bump github.com/nats-io/nats-server/v2 from 2.10.11 to 2.10.12 in /lib/go
* #2434 java-lib: bump io.nats:jnats from 2.17.3 to 2.17.4 in /lib/java
* #2432 java-lib: bump io.netty:netty-all from 4.1.107.Final to 4.1.108.Final in /lib/java
* #2428 go-test: bump github.com/nats-io/nats.go from 1.33.1 to 1.34.0 in /test/integration
* #2431 go-exam: bump github.com/apache/thrift from 0.19.0 to 0.20.0 in /examples/go
* #2433 java-lib: bump org.apache.thrift:libthrift from 0.19.0 to 0.20.0 in /lib/java
* #2429 py-lib: bump thrift from 0.16.0 to 0.20.0 in /lib/python
* #2426 go-lib: bump github.com/nats-io/nats.go from 1.33.1 to 1.34.0 in /lib/go
* #2435 java: Avoid suppressed exceptions after a servlet write exception
* #2430 go-exam: bump github.com/nats-io/nats.go from 1.33.1 to 1.34.0 in /examples/go
* #2437 java-lib: bump org.apache.maven.plugins:maven-gpg-plugin from 3.2.1 to 3.2.2 in /lib/java
* #2438 FEA-3546: Remove deprecation log from generated dart libs

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by danielharasymiw-wf — COMMENTED** [review]
QA +1

**Comment by danielharasymiw-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
