### PR TITLE
INFENG-5475 Release 2.18.0

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/INFENG-5475

@Workiva/messaging-pp

* #991 Upgrade aio dependencies
* #1 Fix travis builds for forks, don't publish if not Workiva/frugal, add top level Makefile
* #994 Support deprecated annotation for enum values
* #993 Glide examples

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by brianshannan-wf** [comment]
+1 @Workiva/messaging-pp @Workiva/product2 @theisensanders-wf @brettkail-wk

**Comment by stevenosborne-wf** [comment]
lgtm

**Comment by brianshannan-wf** [comment]
+1

**Pull request merged**
