### PR TITLE
INFENG-8047 Remove pypi url env variable, as twine defaults to the correct one.

### PR DESCRIPTION
**Pull request by charliestrawn-wf**
Fixes pypi timeout

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
+1

**Comment by danielnovotny-wf** [comment]
+1

**Comment by charliestrawn-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
