### PR TITLE
INFENG-7388 Release 2.28.0

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/INFENG-7388

@Workiva/product2

* #1083 INFENG-6712 Add language options to java/go to suppress deprecated logging
* #1085 Revert https://github.com/Workiva/frugal/pull/1040
* #1086 Tornado correct exceptions

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
