### PR TITLE
Upgrade asyncio-nats-client dependency

### PR DESCRIPTION
**Pull request by aaronkavlie-wf**
### Story:
I experience stale connection errors and timeouts after a NATS connection stayed open for a while (on Python with asyncio).

[This issue](https://github.com/nats-io/nats.py/issues/93) was the root cause, and force-upgrading `asyncio-nats-client` in my code base resolved the issue.

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
N/A

### How To Test:
N/A

### My Test Results:
N/A

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by aaronkavlie-wf** [comment]
@rmconsole-wf

**Comment by aaronkavlie-wf** [comment]
@brianshannan-wf any idea what's causing the build failures here?

**Comment by brianshannan-wf** [comment]
I'm not sure, it seems to be passing for other pull requests. Maybe try merging in the latest develop?

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
