### PR TITLE
java: Suppress @Generated by default

### PR DESCRIPTION
**Pull request by brettkail-wk**
### Story:
See commit messages for details.  Commits are intended to be reviewed independently.

### Acceptance Criteria:
- [x] At least one InfRe Squad 2 member has reviewed and +1'd
- [x] Code has been tested and results documented
- [x] Unit tests have been updated
- [ ] ~~Updates to documentation if necessary~~
- [x] Verify and document changes to any other Messaging components
- [x] Pull request made against the 'develop' branch, not master

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
+1
I believe it makes sense to change the default due to the change in javas behaviour and the fact that the annotations don't have a functional purpose anyway.

Thanks for the pr!

**Comment by yuanmwang-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
