### PR TITLE
FEDX-423: Fix -gen dart:null_for_unset,nullsafe

### PR DESCRIPTION
**Pull request by brettkail-wk**
### Story:
This is a different fix for #2338.  Commits are intended to be reviewed independently:
- The first commit adds new tests for `required` for `list`/`set`/`map` fields and regenerates baselines.
- The next two commits add a new `dart.nullunsetsafe` with `dart:null_for_unset,nullsafe
- The next commit is a minor refactor
- The final commit changes the logic to fix `dart:null_for_unset,nullsafe`.  There are harmless changes to `dart.nullunset` and there are meaningful changes to `dart.nullunsetsafe`.

#### Reviewers:
@Workiva/service-platform
@alishadalal-wk @robbecker-wf @patkujawa-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]
+10 tested in licensing_frugal and the one where this problem was detected: attachment_packager_frugal
No analysis problems in either.

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
