### PR TITLE
INFENG-11460: Move mockito to dev dependency

### PR DESCRIPTION
**Pull request by corwinsheahan-wf**
### Story:
`mockito` is not needed as a normal dep and should be downgraded to a dev dep.

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
TODO

### How To Test:
CI Passing should be sufficient.

### My Test Results:
TODO

#### Reviewers:
@evanweible-wf @maxwellpeterson-wf 
@Workiva/product2

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>2 vulns in <code>org.apache.thrift:libthrift < 0.12.0</code> via <code>examples/java/pom.xml</code></li>
<li>2 vulns in <code>org.apache.thrift:libthrift < 0.12.0</code> via <code>lib/java/pom.xml</code></li>
<li>2 vulns in <code>org.apache.thrift:libthrift < 0.12.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by josephswanson-wf** [comment]
+1 QA passing CI sufficient

**Comment by corwinsheahan-wf** [comment]
QA +1
* CI passes is sufficient for dep only change.

Merging into develop.
@Workiva/release-management-p

**Comment by josephswanson-wf** [comment]
@Workiva/release-management-p

**Comment by corwinsheahan-wf** [comment]
@Workiva/release-management-p bump

**Pull request merged**
