### PR TITLE
dart: Add --gen dart:use_int64

### PR DESCRIPTION
**Pull request by brettkail-wk**
### Story:
The Dart `TProtocol.readI64`/`.writeI64` methods return `int`.  When compiling with dart2js, this uses plain JavaScript numbers, so values outside MIN_SAFE_INTEGER/MAX_SAFE_INTEGER are not returned faithfully.

### Acceptance Criteria:
- [x] Code has been tested and results documented
- [x] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
Commits are intended to be reviewed independently.  In particular, the second commit adding the `dart.int64` commit will make the "File Changed" tab unreadable.

The generated code depends on extension `TProtocol.readI64`/`.writeI64`, which are available in the hosted 0.0.14 Thrift version referenced by `addToPubspec`.

The generated Dart code uses `fixnum.Int64` as part of the API.  That is a backwards incompatible change, so a `use_int64` option is added so that the effects of the change can be managed.

### How To Test:
I manually tested this with an internal application that uses large numbers.

### My Test Results:
Large numbers can be decoded properly by generated Dart using the `--gen dart:use_int64` option.

#### Reviewers:
@Workiva/service-platform

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by adamdockter-wk — APPROVED** [review]
Looks good, thanks for the all testing.

**Comment by brettkail-wk** [comment]
QA +1 Tested as described in the PR description.

**Comment by brettkail-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
