### PR TITLE
CPLAT-5534: Cast inner types on returned futures

### PR DESCRIPTION
**Pull request by corwinsheahan-wf**
### Story:
Frugal's dart generation generates accessor methods which return Future's containing some requested data. Here's a typical example:
```
Future<List<t_comments.UserData>> getUserDataForAccount(frugal.FContext ctx) {
    return this._methods['getUserDataForAccount']([ctx]) as Future<List<t_comments.UserData>>;
}
```

Unfortunately, the cast can only infer the wrapping type (`Future`) and not the underlying type parameter. This causes the returned type to be inferred as `Future<dynamic>`, regardless of the actual type parameter, leading to runtime errors like this on Dart 2:
```
error: Type '_Future<dynamic>' should be '_Future<List<t_comments.UserData>>' to implement expected type 'Future<List<t_comments.UserData>>'.
```
To fix this, we add a `.then` and explicitly cast the type parameter in a supplied callback. This does not affect async timing, and provides the correct typing.

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### How To Test:
* Generate `comments_frugal` using this branch's generator, and smoke test examples on Dart 1 on master, and Dart 1 & Dart 2 on [this](https://github.com/Workiva/w_comments/tree/dart2) branch.

### My Test Results:
TODO

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
