### PR TITLE
INFENG-8139 Release 3.4.1

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/INFENG-8139

@Workiva/product2

* #1116 Consume jnats 2.4.6
* #1117 Initialize ephemeralProperties in NewFContext

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
