### PR TITLE
Revert https://github.com/Workiva/frugal/pull/1040

### PR DESCRIPTION
**Pull request by yuanmwang-wf**
### Story:
Reverts https://github.com/Workiva/frugal/pull/1040

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
@patkujawa-wf @nathancoleman-wf I think you were interested in this

**Comment by brianshannan-wf** [comment]
Revert seems good to me, +1

**Comment by patkujawa-wf** [comment]
+1 CR.

FYI @natewoods-wf @benechols-wf @todbachman-wf @behdadshayegan-wf @shanesizer-wf, since I think the original PR arose from performance squad desires.

**Comment by natewoods-wf** [comment]
I don't see any reasoning for a revert, is there any documentation/comments on why this is being reverted?

**Comment by yuanmwang-wf** [comment]
@natewoods-wf There were discussions here: https://github.com/Workiva/frugal/pull/1082

Also the original discussion here: https://workiva.slack.com/archives/CEFTREXT8/p1550518577001400

**Comment by brianshannan-wf** [comment]
Unless there's any strong objections I'd like to merge this and cut a release. We have enough on our plate right now that we can't prioritize digging into a fix that keeps the correct behaviour and throughly testing that. I would prefer the behaviour be correct in the mean time

**Comment by stevenosborne-wf** [comment]
+1

**Pull request merged**
