### PR TITLE
INFENG-4464 Release 2.10.0

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/INFENG-4464

@Workiva/messaging-pp

* #909 Use go1.9 in runner image
* #911 RED-1848: update aviary.yaml with proper excludes
* #915 Use older version of travis worker so build passes
* #914 don't show dependencies multiple times in the html index
* #918 Add serialize functions with tests
* #921 java: Add missing space to unhandled exception log
* #923 Don't encrypt environment vars that don't need to be and document the ones that are.
* #922 java: Add FHttpTransportHeaders.getRequestHeaders(FContext)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 1</summary>
<li>Watched file aviary.yaml modified</li>
</details>

**Comment by brianshannan-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
@jeffreymelvin-wf @matthewlorimor-wf could you infosec review this due to the aviary.yaml change you guys made?

**Comment by charliestrawn-wf** [comment]
Security +1

**Comment by matthewlorimor-wf** [comment]
Security +1

**Pull request merged**
