### PR TITLE
java: Avoid comment for default requiredness

### PR DESCRIPTION
**Pull request by brettkail-wk**
It is confusing to output a `// required` comment for fields that have default requiredness.

@Workiva/messaging-pp

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Module Findings
No security relevant content detected. Please review for security relevance and request security review as needed.

**Comment by brianshannan-wf** [comment]
+1. I think those comments were a remnant of duplicating code thrift produced. This does change the presence modifier passed to the type function, but I don't think that should change anything

**Comment by charliestrawn-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Pull request merged**
