### PR TITLE
MEX-907 Release v3.16.17

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/MEX-907

@Workiva/product2

* #2159 Revert "java-lib: bump jnats from 2.16.8 to 2.16.9 in /lib/java"
* #2155 java-lib: bump jacoco-maven-plugin from 0.8.8 to 0.8.9 in /lib/java
* #2160 skip broken version for jnats
* #2154 java-lib: bump netty-all from 4.1.90.Final to 4.1.91.Final in /lib/java
* #2163 go-tool: bump golang.org/x/tools from 0.7.0 to 0.8.0
* #2162 py-lib: bump coverage from 7.2.2 to 7.2.3 in /lib/python
* #2161 java-lib: bump jnats from 2.16.8 to 2.16.9 in /lib/java
* #2157 Allow the customization of the maximum message size in FDefaultNettyHttpProcessor

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by toddbeckman-wf — APPROVED** [review]

**Comment by toddbeckman-wf** [comment]
QA +1

**Comment by toddbeckman-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
