### PR TITLE
Cleanup old build files

### PR DESCRIPTION
**Pull request by ci-push-wf**
## Overview
This PR is to remove the remnants of the Smithy and Shipyard Build system, specifically to remove smithy.yaml and shipyard.yaml files and references.
We will not be following up on these prs, so please reach out in the Support: Build Tools hipchat room with any questions.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by yuanmwang-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1

**Comment by blakeroberts-wk** [comment]
+1

**Comment by blakeroberts-wk** [comment]
@Workiva/release-management-p

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
