### PR TITLE
SPLAT-1134 Release v3.14.4

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/SPLAT-1134

@Workiva/product2

* #1559 java-test: bump activemq-client from 5.16.1 to 5.16.2 in /test/integration/java/frugal-integration-test
* #1561 java-exam: bump activemq-client from 5.16.1 to 5.16.2 in /examples/java
* #1558 java-test: bump jnats from 2.10.0 to 2.11.0 in /test/integration/java/frugal-integration-test
* #1560 java-lib: bump jnats from 2.10.0 to 2.11.0 in /lib/java
* #1557 SPLAT-1140 Dart: Don't complete already-completed completers

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>lib/java/pom.xml</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by charliekump-wf — APPROVED** [review]
+10 Reviewed last commit and CI Passes

@Workiva/release-management-p ready for merge.

**Review by houstonking-wf — APPROVED** [review]
The QA +1 for #1557 is transitive here: https://github.com/Workiva/frugal/pull/1557#issuecomment-832792220

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
