### PR TITLE
INFENG-8959 Release 3.4.7

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/INFENG-8959

@Workiva/product2

* #1140 INFENG-9206 use "this." for fields when possible

### CODE REVIEW

**Comment by kevinfrommelt-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.
<details>
<summary>Error scanning for image validation issues</summary>
</details>

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
aviary

**Comment by brianshannan-wf** [comment]
aviary

**Comment by todbachman-wf** [comment]
@aviary-wf

**Comment by brianshannan-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
