### PR TITLE
SPLAT-2855 Release v3.14.15

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/SPLAT-2855

@Workiva/product2

* #1804 java-exam: bump netty-all from 4.1.73.Final to 4.1.74.Final in /examples/java
* #1793 java-test: bump gson from 2.8.9 to 2.9.0 in /test/integration/java/frugal-integration-test
* #1791 java-test: bump netty-all from 4.1.73.Final to 4.1.74.Final in /test/integration/java/frugal-integration-test
* #1795 java-test: bump slf4j-simple from 1.7.35 to 1.7.36 in /test/integration/java/frugal-integration-test
* #1796 java-lib: bump slf4j-simple from 1.7.35 to 1.7.36 in /lib/java
* #1800 java-lib: bump maven-compiler-plugin from 3.9.0 to 3.10.0 in /lib/java
* #1803 java-exam: bump maven-compiler-plugin from 3.9.0 to 3.10.0 in /examples/java
* #1799 java-lib: bump nexus-staging-maven-plugin from 1.6.8 to 1.6.10 in /lib/java
* #1798 java-lib: bump netty-all from 4.1.73.Final to 4.1.74.Final in /lib/java
* #1801 java-exam: bump slf4j-api from 1.7.35 to 1.7.36 in /examples/java
* #1805 java-lib: bump gson from 2.8.9 to 2.9.0 in /lib/java
* #1792 java-test: bump maven-compiler-plugin from 3.9.0 to 3.10.0 in /test/integration/java/frugal-integration-test
* #1807 java-test: bump activemq-client from 5.16.3 to 5.16.4 in /test/integration/java/frugal-integration-test
* #1809 java-lib: bump nexus-staging-maven-plugin from 1.6.10 to 1.6.11 in /lib/java
* #1811 java-lib: bump maven-javadoc-plugin from 3.3.1 to 3.3.2 in /lib/java
* #1814 java-exam: bump activemq-client from 5.16.3 to 5.16.4 in /examples/java

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(5) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
<li>1 vulns in <code>github.com/nats-io/nats-server/v2 < 2.7.2</code> via <code>lib/go/go.mod</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>lib/java/pom.xml</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
<li>1 vulns in <code>org.nanohttpd:nanohttpd</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code> with no fix reported by GitHub</li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by charliekump-wf — APPROVED** [review]
+1 Release/tagging dependency updates only.

**Comment by charliekump-wf** [comment]
@Workiva/release-management-p ready for merge.

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
