### PR TITLE
MEX-1486 Release v3.17.6

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/MEX-1486

@Workiva/product2

* #2343 go-lib: bump github.com/nats-io/nats-server/v2 from 2.10.2 to 2.10.3 in /lib/go
* #2342 go-lib: bump github.com/nats-io/nats.go from 1.30.2 to 1.31.0 in /lib/go
* #2345 java-lib: bump io.netty:netty-all from 4.1.99.Final to 4.1.100.Final in /lib/java
* #2346 java-lib: bump org.jacoco:jacoco-maven-plugin from 0.8.10 to 0.8.11 in /lib/java
* #2344 go-test: bump github.com/nats-io/nats.go from 1.30.2 to 1.31.0 in /test/integration
* #2341 go-exam: bump github.com/nats-io/nats.go from 1.30.2 to 1.31.0 in /examples/go
* #2347 java-lib: bump io.nats:jnats from 2.17.0 to 2.17.1 in /lib/java
* #2352 Dart 2.19
* #2353 java-lib: bump org.apache.maven.plugins:maven-checkstyle-plugin from 3.3.0 to 3.3.1 in /lib/java
* #2354 go-lib: bump github.com/nats-io/nats-server/v2 from 2.10.3 to 2.10.4 in /lib/go
* #2359 Cache parsed include files
* #2363 go-lib: bump github.com/nats-io/nats-server/v2 from 2.10.4 to 2.10.5 in /lib/go
* #2360 java-lib: bump org.apache.maven.plugins:maven-javadoc-plugin from 3.6.0 to 3.6.2 in /lib/java
* #2362 go-tool: bump golang.org/x/tools from 0.14.0 to 0.15.0
* #2361 java-lib: bump io.netty:netty-all from 4.1.100.Final to 4.1.101.Final in /lib/java
* #2370 java-lib: bump org.apache.maven.plugins:maven-javadoc-plugin from 3.6.2 to 3.6.3 in /lib/java
* #2368 go-tool: bump golang.org/x/tools from 0.15.0 to 0.16.0
* #2369 go-lib: bump github.com/nats-io/nats-server/v2 from 2.10.5 to 2.10.6 in /lib/go
* #2372 go-lib: bump github.com/nats-io/nats-server/v2 from 2.10.6 to 2.10.7 in /lib/go
* #2371 java: Add -gen java:default_unsupported

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(2) Security relevant changes were detected</summary>
<li>Watched keyword <code>ObjectOutputStream</code> in <code>compiler/testdata/expected/java/variety_defaultunsupported/FFoo.java</code> line(s) ['1115', '1331', '1765', '2243', '2658', '3071', '3475', '3934', '4265', '4677', '5033', '5273', '5565', '5795', '6086', '6393', '6699', '7002', '7305', '7608', '7911', '8214', '8517'] added</li>
<li>Watched keyword <code>ObjectInputStream</code> in <code>compiler/testdata/expected/java/variety_defaultunsupported/FFoo.java</code> line(s) ['1123', '1339', '1773', '2251', '2666', '3079', '3483', '3942', '4273', '4685', '5041', '5281', '5573', '5803', '6094', '6401', '6707', '7010', '7313', '7616', '7919', '8222', '8525'] added</li>
</details>

## Action Items
* Obtain a [security review](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); reviewer should pay special attention to insights listed above
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by danielharasymiw-wf — APPROVED** [review]
QA +1

**Comment by toddbeckman-wf** [comment]
Security +1
The data caught by aviary is just test data and is not released as usable code outside this repo

**Comment by danielharasymiw-wf** [comment]
@Workiva/release-management-p

**Review by danielharasymiw-wf — APPROVED** [review]

**Comment by danielharasymiw-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
