### PR TITLE
Upgrade aiohttp range

### PR DESCRIPTION
**Pull request by charliekump-wf**
### Story:
Teams wanting newer versions of aiohttp.

### Acceptance Criteria:
- [x] Code has been tested and results documented
- [x] Unit tests have been updated
- [x] Updates to documentation if necessary
- [x] Verify and document changes to any other Messaging components
- [x] Pull request made against the 'develop' branch, not master

### Design Notes:
N/A

### How To Test:
Tests updated

### My Test Results:
Test Pass

#### Reviewers:
@Workiva/service-platform

### CODE REVIEW

**Review by ivanvandessel-wk — APPROVED** [review]
+1

**Review by jimellwood-wk — APPROVED** [review]
+1

**Comment by charliekump-wf** [comment]
@Workiva/release-management-p ready for merge.

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
