### PR TITLE
INFENG-7980 Release 3.3.2

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/INFENG-7980

@Workiva/product2

* #1111 INFENG-8001 Fix build
* #1112 CPLAT-5534: Cast inner types on returned futures

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by brianshannan-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
