### PR TITLE
INFENG-6712 Add language options to java/go to suppress deprecated logging

### PR DESCRIPTION
**Pull request by stevenosborne-wf**
### Story:
Add an option to the Frugal generator to toggle whether or not warnings are logged when a deprecated endpoint is used. This would be particularly useful when a heavily-used endpoint is deprecated by a team that already has metrics to tell it how frequently that endpoint is being called.

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
TODO

### How To Test:
Check generated code

### My Test Results:
All clear

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by stevenosborne-wf** [comment]
FYI: @tomdeering-wf

**Comment by brianshannan-wf** [comment]
+1

**Comment by blakeroberts-wk** [comment]
+1

**Comment by blakeroberts-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
