### PR TITLE
INFENG-6094 publish build artifacts

### PR DESCRIPTION
**Pull request by blakeroberts-wk**
https://jira.atl.workiva.net/browse/INFENG-6094

@Workiva/messaging-pp @Workiva/product2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by matthewschlue-wf** [comment]
+10

**Comment by brianshannan-wf** [comment]
Do we need to publish these under `BUILD_ARTIFACTS_BUILD` too as well as `AUDIT`? Is only one place good?

**Comment by matthewschlue-wf** [comment]
I think under the scope of this they're more concerned with it being under `audit` https://dev.workiva.net/docs/teams/release-management/dependency-tracking/build-artifacts
So we would probably be good only having it in one

**Comment by matthewschlue-wf** [comment]
+10

**Comment by brianshannan-wf** [comment]
+1

**Comment by matthewschlue-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
