### PR TITLE
SAPI-1500: Update testing

### PR DESCRIPTION
**Pull request by charliekump-wf**
# [SAPI-1500](https://jira.atl.workiva.net/browse/SAPI-1500)
Issue Status

### Story:
- With Go 1.13+, flag.Parse is handled differently and the way the testing is written here needs to be updated to work.
- Also a few changes to the release scripts (to reflect similar changes to messaging-sdk release scripts).

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
N/A

### How To Test:
- Using Go 1.13+, run `python ./scripts/update.py --version v3.9.5`

### My Test Results:
- Update process succeeded with expected results.

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>2 vulns in <code>org.apache.thrift:libthrift < 0.12.0</code> via <code>examples/java/pom.xml</code></li>
<li>2 vulns in <code>org.apache.thrift:libthrift < 0.12.0</code> via <code>lib/java/pom.xml</code></li>
<li>2 vulns in <code>org.apache.thrift:libthrift < 0.12.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by charliekump-wf** [comment]
@Workiva/release-management-p ready for merge.

**Comment by josephswanson-wf** [comment]
c'mon @rmconsole-wf

**Comment by josephswanson-wf** [comment]
updated rmconsole.. @Workiva/release-management-p go for it

**Pull request merged**
