### PR TITLE
WIP DOCPLAT-3307 Get rid of library/part syntax; expose more APIs.

### PR DESCRIPTION
**Pull request by patkujawa-wf**
This is just a concept for discussion.

Apparently, using library/part allows access to private variables, so
I made several of them public (but with doc-comments indicating that
they should be considered "package private").

This was all just to enable exporting only one of the Headers APIs
rather than the entire class!

@Workiva/messaging-pp

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by patkujawa-wf** [comment]
ERROR: No Dockerfile found in the root directory. Tried "workivabuild.Dockerfile" and "Dockerfile"

**Comment by patkujawa-wf** [comment]
[4:45 PM] Pat Kujawa: (facepalm) someone turned off smithy builds
[4:45 PM] Pat Kujawa: https://ci.webfilings.com/Workiva/frugal

**Comment by patkujawa-wf** [comment]
https://ci.webfilings.com/build/1319927 is the reals smithy/pr

**Comment by brianshannan-wf** [comment]
I'm curious what your use case for consuming the Headers class outside of frugal is, as it's a pretty low level interface

**Comment by patkujawa-wf** [comment]
@brianshannan-wf yeah, it's not a common one I assume, but https://github.com/Workiva/skaardb/pull/6209/commits/3cad4c25af16babf0ccd90c0f7fd70b5c842e788 hopefully gives some context. Basically, we're challenged with being able to do messaging in gopherjs'd Go code without access to Go's networking libs, so we need to provide messaging transport via Dart and inject it into Go. As you can see in that commit, there is a workaround via public API, so maybe that's good enough.

```diff
diff --git a/lib/src/doc_plat_client/doc_plat_client.dart b/lib/src/doc_plat_client/doc_plat_client.dart
index 22ffe0449e8..cee5640b25c 100644
--- a/lib/src/doc_plat_client/doc_plat_client.dart
+++ b/lib/src/doc_plat_client/doc_plat_client.dart
@@ -34,8 +34,6 @@ import 'package:w_common/disposable.dart';
 import 'package:w_session/w_session.dart';
 import 'package:w_transport/w_transport.dart' as wt;
 import 'package:wdesk_sdk/experience_framework.dart';
-// TODO: have messaging team expose Headers for our consumption.
-import 'package:frugal/src/frugal.dart' show Headers;
 import 'package:skaardb/alpha/doc_engine.dart' show NetCallback, NetCallFunc;
 
 typedef Future<int> _OperationExecutor();
@@ -2740,8 +2738,9 @@ Future<networkfunc> directHttpNetwork(wt.HttpClient client, String serviceUri) a
   var serviceProvider = messaging.newHttpClient(serviceDescriptor, client);
   await serviceProvider.transport.open();
   return (Uint8List payload, NetCallback cb) {
-    var ctx = new frugal.FContext();
-    ctx.addRequestsHeaders(Headers.decodeFromFrame(payload.sublist(4)));
+    var transport = new frugal.TMemoryTransport.fromUint8List(payload);
+    var fProtocol = new frugal.FProtocol(new thrift.TBinaryProtocol(transport));
+    var ctx = fProtocol.readRequestHeader();
     serviceProvider.transport.request(ctx, payload).then((TTransport a) {
       // Read the first 4 bytes for the length of the message.
       var msgLen = new Uint8List(4);
@@ -2780,8 +2779,9 @@ Future<networkfunc> directNatsNetwork(String service, messaging.NatsMessagingCli
   var buffer = new Uint8List(1024 * 1024);
 
   return (Uint8List payload, NetCallback cb) {
-    var ctx = new frugal.FContext();
-    ctx.addRequestsHeaders(Headers.decodeFromFrame(payload.sublist(4)));
+    var transport = new frugal.TMemoryTransport.fromUint8List(payload);
+    var fProtocol = new frugal.FProtocol(new thrift.TBinaryProtocol(transport));
+    var ctx = fProtocol.readRequestHeader();
     serviceProvider.transport.request(ctx, payload).then((TTransport a) {
       var n = a.read(buffer, 0, buffer.length);
       if (n == 0) {
```

**Comment by patkujawa-wf** [comment]
Looks like we can get around this by using public API, so we don't need to pursue this change.

    var transport = new frugal.TMemoryTransport.fromUint8List(payload);
    var fProtocol = new frugal.FProtocol(new thrift.TBinaryProtocol(transport));
    var ctx = fProtocol.readRequestHeader();

**Pull request closed without merging**
