### PR TITLE
MEX-369 Release v3.16.1

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/MEX-369

@Workiva/product2

* #1948 go-test: bump github.com/sirupsen/logrus from 1.8.1 to 1.9.0 in /test/integration
* #1946 go-tool: bump github.com/sirupsen/logrus from 1.8.1 to 1.9.0
* #1947 go-exam: bump github.com/sirupsen/logrus from 1.8.1 to 1.9.0 in /examples/go
* #1945 go-lib: bump github.com/sirupsen/logrus from 1.8.1 to 1.9.0 in /lib/go
* #1949 MEX-395 config size

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
<details>
<summary>(6) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
<li>1 vulns in <code>aiohttp</code> via <code>lib/python/requirements_dev_asyncio.txt</code> with no fix reported by GitHub</li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>lib/java/pom.xml</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
<li>1 vulns in <code>org.nanohttpd:nanohttpd</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code> with no fix reported by GitHub</li>
<li>2 vulns in <code>github.com/nats-io/nats-server/v2 < 2.7.4</code> via <code>lib/go/go.mod</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by adamdockter-wk** [comment]
QA +1 - All PRs have QA signoff

**Review by adamdockter-wk — APPROVED** [review]

**Comment by adamdockter-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
