### PR TITLE
Raise w_transport min to ^4.0.0

### PR DESCRIPTION
**Pull request by sourcegraph-wk**
Client Platform is updating dependencies! 
This PR raises the min version allowed for w_transport to ^4.0.0
```
  pubspec_codemod raise-min w_transport 4.0.0 --recursive
```
For more info, reach out to `#support-client-plat` on Slack.

[_Created by Sourcegraph batch change `Workiva/w_transport_v4_raise_min`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/w_transport_v4_raise_min)

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
<details>
<summary>(4) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>lib/java/pom.xml</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
<li>1 vulns in <code>org.nanohttpd:nanohttpd</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code> with no fix reported by GitHub</li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by robbecker-wf** [comment]
QA+1 CI Passes

**Review by alanknight-wk — APPROVED** [review]

**Review by corwinsheahan-wf — APPROVED** [review]

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
