### PR TITLE
Add ignore statement to workaround dart sdk issue

### PR DESCRIPTION
**Pull request by corwinsheahan-wf**
### Story:
It was recently discovered that the Dart code generated by this repo falsely triggers an analysis failure in some cases. This is a [known dartlang issue](https://github.com/dart-lang/sdk/issues/29751) that has been fixed in Dart 2.8.0 and later. 

Since we still support Dart 2.7.2, we need to workaround this issue by adding an ignore statement. 

This issue only affects analysis, and is not a run time error, so it is safe to ignore. 

Once support for Dart 2.7.2 is dropped, this warning can and should be removed. 

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
TODO

### How To Test:
TODO

### My Test Results:
TODO

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by maxwellpeterson-wf — APPROVED** [review]

**Review by aaronstgeorge-wf — APPROVED** [review]

**Review by charliekump-wf — APPROVED** [review]
+1

@Workiva/release-management-p ready for merge.

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Comment by seanstrickland-wf** [comment]
QA +1

Tested locally and it fixed the dart analysis error I was seeing.

**Pull request merged**
