### PR TITLE
SPLAT-195 Release v3.11.1

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/SPLAT-195

@Workiva/service-platform 

* #1340 Fixes mvn package to be usable by JDKs greater than 1.8
* #1349 Go: Bump github.com/nats-io/nats-server/v2 from 2.1.7 to 2.1.8 in /lib/go
* #1347 Java: Bump jmh.version from 1.25.1 to 1.25.2 in /lib/java
* #1346 Java: Bump jnats from 2.7.0 to 2.8.0 in /lib/java
* #1348 Java: Bump mockito-core from 3.5.7 to 3.5.10 in /lib/java
* #1353 Python: Bump coverage from 5.2.1 to 5.3 in /lib/python
* #1354 Examples: Bump netty-all from 4.1.51.Final to 4.1.52.Final in /examples/java
* #1356 Java: Bump checkstyle from 8.36 to 8.36.1 in /lib/java
* #1357 Java: Bump netty-all from 4.1.51.Final to 4.1.52.Final in /lib/java
* #1358 Tests: Bump netty-all from 4.1.51.Final to 4.1.52.Final in /test/integration/java/frugal-integration-test
* #1355 Python: Bump asyncio-nats-client from 0.10.0 to 0.11.2 in /lib/python
* #1352 SPLAT-65: GO: encapsulate Flush (thrift 0.13.0 preparation)
* #1359 Got cross and cross-local tests working on my box
* #1362 Java: Bump jacoco-maven-plugin from 0.8.5 to 0.8.6 in /lib/java
* #1363 Java: Bump mockito-core from 3.5.10 to 3.5.11 in /lib/java
* #1360 3.10.X Changes for Java
* #1365 Update for IR: v3.10.0 to v3.10.1
* #1361 IR v3.10.1: More thrift 0.13.0 preparation
* #1366 Pull in v3.10.1 IR
* #1367 SPLAT-187 Consume new thrift dart
* #1371 Java: Bump mockito-core from 3.5.11 to 3.5.13 in /lib/java
* #1369 SPLAT-189: Go: Thrift 0.13.0
* #1351 SPLAT-81: Python thrift 0.13.0
* #1370 Java: Bump checkstyle from 8.36.1 to 8.36.2 in /lib/java

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by natewoods-wf — APPROVED** [review]

**Review by charliekump-wf — APPROVED** [review]
+1

**Comment by charliekump-wf** [comment]
@Workiva/release-management-p ready for merge.

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
