### PR TITLE
Add split mock versions, move py2 reqs file

### PR DESCRIPTION
**Pull request by charliekump-wf**
### Story:
Python 2 compatibility surfacing in newer versions of packages. Add split supported mock version, move req file for python 2 to directory to avoid dependabot bumps.

### Acceptance Criteria:
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

#### Reviewers:
@Workiva/service-platform @ivanvandessel-wk

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by ivanvandessel-wk — APPROVED** [review]
QA +1

**Comment by ivanvandessel-wk** [comment]
Just like we discussed moving to a different folder structure

**Review by ivanvandessel-wk — APPROVED** [review]
QA +1

**Comment by charliekump-wf** [comment]
@Workiva/release-management-p ready for merge.

**Comment by charliekump-wf** [comment]
+1 ?

**Review by jimellwood-wk — APPROVED** [review]
+1

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Review by ivanvandessel-wk — COMMENTED** [review]
Looks like a good way to manage the python2 dependencies until we remove them end of the year

**Pull request merged**
