### PR TITLE
MEX-540 Release v3.16.4

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/MEX-540

@Workiva/product2

* #1984 java-lib: bump mockito-core from 4.7.0 to 4.8.0 in /lib/java
* #1989 go-lib: bump github.com/nats-io/nats-server/v2 from 2.8.4 to 2.9.0 in /lib/go
* #1991 java-test: bump netty-all from 4.1.80.Final to 4.1.82.Final in /test/integration/java/frugal-integration-test
* #1993 java-test: bump jnats from 2.15.6 to 2.15.7 in /test/integration/java/frugal-integration-test
* #1992 java-test: bump jetty-servlet from 9.4.35.v20201120 to 9.4.49.v20220914 in /test/integration/java/frugal-integration-test
* #1994 java-lib: bump jnats from 2.15.6 to 2.15.7 in /lib/java
* #2000 go-test: bump github.com/nats-io/nats.go from 1.16.0 to 1.17.0 in /test/integration
* #1977 java-exam: bump activemq-client from 5.16.4 to 5.17.2 in /examples/java
* #1995 java-lib: bump netty-all from 4.1.80.Final to 4.1.82.Final in /lib/java
* #1978 go-tool: bump github.com/urfave/cli from 1.22.9 to 1.22.10
* #2001 go-exam: bump github.com/nats-io/nats.go from 1.16.0 to 1.17.0 in /examples/go
* #1996 java-exam: bump netty-all from 4.1.80.Final to 4.1.82.Final in /examples/java
* #2004 java-test: bump jnats from 2.15.7 to 2.16.0 in /test/integration/java/frugal-integration-test
* #2003 w_common v2 rollout - 1 of 2 raise max
* #2007 java-lib: bump jnats from 2.15.7 to 2.16.0 in /lib/java

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(6) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
<li>1 vulns in <code>aiohttp</code> via <code>lib/python/requirements_dev_asyncio.txt</code> with no fix reported by GitHub</li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>lib/java/pom.xml</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
<li>1 vulns in <code>org.nanohttpd:nanohttpd</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code> with no fix reported by GitHub</li>
<li>2 vulns in <code>github.com/nats-io/nats-server/v2 < 2.7.4</code> via <code>lib/go/go.mod</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by toddbeckman-wf — APPROVED** [review]

**Comment by toddbeckman-wf** [comment]
QA +1

**Comment by toddbeckman-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
