### PR TITLE
SPLAT-2229 Release v3.14.12

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/SPLAT-2229

@Workiva/product2

* #1742 go-tool: bump golang.org/x/tools from 0.1.7 to 0.1.8
* #1741 go-lib: bump github.com/nats-io/nats-server/v2 from 2.6.5 to 2.6.6 in /lib/go
* #1744 Raise w_transport min to ^4.0.0
* #1745 java-test: bump netty-all from 4.1.70.Final to 4.1.71.Final in /test/integration/java/frugal-integration-test
* #1747 java-exam: bump netty-all from 4.1.70.Final to 4.1.71.Final in /examples/java
* #1746 java-lib: bump netty-all from 4.1.70.Final to 4.1.71.Final in /lib/java
* #1748 Raise Max Versions

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
<details>
<summary>(4) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>lib/java/pom.xml</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
<li>1 vulns in <code>org.nanohttpd:nanohttpd</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code> with no fix reported by GitHub</li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by danielharasymiw-wf — APPROVED** [review]

**Review by evanweible-wf — APPROVED** [review]
QA +1 CI passes

**Comment by danielharasymiw-wf** [comment]
@Workiva/release-management-p

**Comment by danielharasymiw-wf** [comment]
@Workiva/release-management-p ready for merge

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
