### PR TITLE
INFENG-10121: Consume messaging-docker-image 0.0.39

### PR DESCRIPTION
**Pull request by yuanmwang-wf**
### Story:
Consume messaging-docker-image 0.0.39 (updates dart to 2.6.1 and nats-server to 2.1.2)

### Acceptance Criteria:
- [ ] At least one InfRe Squad 2 member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### How To Test:
CI passes

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.
<details>
<summary>Error scanning for image validation issues</summary>
</details>

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by yuanmwang-wf** [comment]
@aviary-wf

**Comment by kevinfrommelt-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
