### PR TITLE
MEX-1448 Release v3.17.3

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/MEX-1448

@Workiva/product2

* #2326 go-lib: bump github.com/nats-io/nats.go from 1.30.1 to 1.30.2 in /lib/go
* #2321 Adjust nullsafe generated code

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by danielharasymiw-wf** [comment]
@Workiva/release-management-p

**Comment by colefeisthamel-wf** [comment]
RM +1

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
