### PR TITLE
MEX-2136 Release v3.17.12

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/MEX-2136

@Workiva/product2

* #2447 java-lib: bump org.jacoco:jacoco-maven-plugin from 0.8.11 to 0.8.12 in /lib/java
* #2446 java-lib: bump org.apache.maven.plugins:maven-source-plugin from 3.3.0 to 3.3.1 in /lib/java
* #2445 go-exam: bump github.com/nats-io/nats.go from 1.34.0 to 1.34.1 in /examples/go
* #2444 go-tool: bump golang.org/x/tools from 0.19.0 to 0.20.0
* #2443 go-lib: bump github.com/nats-io/nats.go from 1.34.0 to 1.34.1 in /lib/go
* #2448 go-test: bump github.com/nats-io/nats.go from 1.34.0 to 1.34.1 in /test/integration
* #2454 go-lib: bump github.com/nats-io/nats-server/v2 from 2.10.12 to 2.10.14 in /lib/go
* #2452 java-lib: bump io.nats:jnats from 2.17.4 to 2.17.6 in /lib/java
* #2453 java-lib: bump org.apache.maven.plugins:maven-gpg-plugin from 3.2.2 to 3.2.3 in /lib/java
* #2451 java-lib: bump io.netty:netty-all from 4.1.108.Final to 4.1.109.Final in /lib/java
* #2449 dart: make element number per file

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by adamdockter-wk — APPROVED** [review]

**Comment by adamdockter-wk** [comment]
QA +1 child PRs QA'd

**Comment by adamdockter-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
