### PR TITLE
Give consumers the option to omit server generation for a parsed service (in golang generation)

### PR DESCRIPTION
**Pull request by joshprzybyszewski-wf**
### Story:
Some clients use the golang generator to generate services, but they're only going to be clients of the IDLs; not servers. Therefore, when we generate the "server" code, we are creating unnecessary artifacts.

Let's give consumers to option to "omit generating the server code" for all services. This should only ever be used by consumers of frugal who are generating code for golang clients.

### Acceptance Criteria:
- [x] Code has been tested and results documented
- [x] Unit tests have been updated
- [x] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### Design Notes:
I've added a single config option to the golang generator which reads it right before it attempts to generate the server code for a service.

### How To Test:
1. Retains backwards compatibility
   - Using the frugal command (without the `omit_server_service_generation` option) outputs the exact same files before and after this PR.
2. Gives an opt-in option to generate less code:
   - While generating go code, use the `omit_server_service_generation` option and see that everything is exactly the same, except now you don't have a server in the generated output.

### My Test Results:
In a private Workiva repo, we see a significant reduction in the amount of unnecessary go code being generated.

#### Reviewers:
@Workiva/service-platform

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(3) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>lib/java/pom.xml</code></li>
<li>1 vulns in <code>org.apache.thrift:libthrift < 0.14.0</code> via <code>test/integration/java/frugal-integration-test/pom.xml</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by benechols-wf — APPROVED** [review]

**Review by natewoods-wf — APPROVED** [review]
I'm aware this has been discussed at length in private, but just so it is known publically, this could also be achieved by removing the `service` sections of `*.frugal` files before generating bindings.  That said, this seems... fine.

**Comment by natewoods-wf** [comment]
@Workiva/release-management-p for merge

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Comment by joshprzybyszewski-wf** [comment]
@natewoods-wf 
> this could also be achieved by removing the service sections of *.frugal files before generating bindings.

Perhaps I'm misunderstanding, but I don't think that's quite true. As a consumer, if I were to remove the `service` definition in the .frugal files when I generate golang frugal code, then I would no longer be generating the `FServiceNameClient` struct. There are cases where I want to still be a client without also being a server.

**Comment by natewoods-wf** [comment]
Ah, correct.  Apologies, my allergy meds are messing with my head.  Nice work!

**Pull request merged**
