### PR TITLE
don't use setter method to set dart default values in the constructor

### PR DESCRIPTION
**Pull request by brianshannan-wf**
Dart was assigning default values to variables in the constructor using the setter method, which sets the `__is_set` flag for that variable. This is undesirable as it means the value will be written across the wire, even though it wasn't assigned to anything. Directly setting the private variable in the constructor fixes this.

@Workiva/product2
@tayloranderson-wf I'm going to need you to QA this

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by yuanmwang-wf** [comment]
+1

**Comment by tayloranderson-wf** [comment]
+10 - Tested this out and it works nicely 😄

**Comment by yuanmwang-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
