### PR TITLE
MSG-488 Release 2.9.2

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.webfilings.com/browse/MSG-488

@Workiva/messaging-pp

* #909 Use go1.9 in runner image
* #911 RED-1848: update aviary.yaml with proper excludes

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 1</summary>
<li>Watched file aviary.yaml modified</li>
</details>

**Comment by brianshannan-wf** [comment]
@jeffreymelvin-wf @matthewlorimor-wf Can we get an infosec review to get the aviary changes you guys made released?

**Comment by oliverjensen-wk** [comment]
Security +1

**Comment by aldenpeterson-wf** [comment]
it seems a bit weird to release a version bump with zero changes that affect consumers, is this release actually necessary?

**Comment by brianshannan-wf** [comment]
Yeah we were just looking at that, plus our travis build started failing for some reason. So we'll scrap this for now

**Pull request closed without merging**
