### PR TITLE
Tornado correct exceptions

### PR DESCRIPTION
**Pull request by brianshannan-wf**
Somehow `self._lock.acquire()` was clearing the current `exc_info`, leading to the actual exception being lost and not raised out of the generated code. Saving the `exc_info` before doing this resolves this problem.

Throwing an exception in a handler locally now gives me:
```
2019-02-27 10:20:43,782 - ERROR - frugal: exception occurred while processing request with correlation id 32097d3f56c646a7bfd0c76fd428830c
Traceback (most recent call last):
  File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/frugal/tornado/processor.py", line 168, in process
    yield processor_function.process(context, iprot, oprot)
  File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/Users/brianshannan/workspaces/wf/go/src/github.com/Workiva/messaging-sdk/examples/python.tornado/gen/v1/music/f_Store.py", line 186, in process
    result.success = yield gen.maybe_future(self._handler([ctx, args.ASIN, args.acct]))
  File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/frugal/middleware.py", line 65, in __call__
    return self._handler(self._proxied_method, *args)
  File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/messaging_sdk/iam/authentication_middleware.py", line 51, in invocation_handler
    return next(method, args)
  File "/Users/brianshannan/dev/wf/msdk-py/lib/python2.7/site-packages/frugal/middleware.py", line 95, in base_handler
    return method(*args)
  File "nats_server.py", line 47, in buyAlbum
    raise ValueError('oops')
ValueError: oops
```

@Workiva/product2
@brettkail-wk if you can confirm this shows the exceptions you want to see that would be great

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by kevinfrommelt-wf** [comment]
+1

**Comment by charliestrawn-wf** [comment]
lgtm 👀

**Comment by stevenosborne-wf** [comment]
+1

**Pull request merged**
