### PR TITLE
SPLAT-187 Consume new thrift dart

### PR DESCRIPTION
**Pull request by aaronstgeorge-wf**
### Story:
Bump minimum thrift version

### Acceptance Criteria:
- [ ] At least one SP member has reviewed and +1'd
- [ ] Code has been tested and results documented
- [ ] Unit tests have been updated
- [ ] Updates to documentation if necessary
- [ ] Verify and document changes to any other Messaging components
- [ ] Pull request made against the 'develop' branch, not master

### How To Test:
You can run the example app

### My Test Results:
seems_to_work

#### Reviewers:
@Workiva/service-platform

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by charliekump-wf — APPROVED** [review]
+1

**Comment by aaronstgeorge-wf** [comment]
@Workiva/release-management-pp 💥

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
