### PR TITLE
Vendor folder shouldn't have a src subfolder.

### PR DESCRIPTION
**Pull request by charliestrawn**
Breaks godep go install.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Module Findings
No security relevant content detected. Please review for security relevance and request security review as needed.

**Comment by brianshannan-wf** [comment]
We should fix the lib dependencies as well, I think we should remove `lib/go/vendor` and `lib/go/Godeps` and add a `lib/go/glide.yaml` file. I can do that if you want

**Comment by brianshannan-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1

**Comment by charliestrawn-wf** [comment]
+1 to kick off smithy

**Pull request closed without merging**
