### PR TITLE
INFENG-6738 INFENG-6739 Release 2.25.0

### PR DESCRIPTION
**Pull request by brianshannan-wf**
@Workiva/product2 @natewoods-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.
<details>
<summary>(1) Image validation issues were detected</summary>
<li>Repo does not appear to install package updates in deployable image</li>
</details>

## Action Items
* Ensure [package updates](https://wiki.atl.workiva.net/display/SECURITY/Security+Requirements+for+Building+Containers#SecurityRequirementsforBuildingContainers-PackageUpdating) are being installed.
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by stevenosborne-wf** [comment]
+1

**Comment by matthewschlue-wf** [comment]
+1

**Comment by matthewschlue-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
