### PR TITLE
STREAMS-1981: Java: Support use_vendor

### PR DESCRIPTION
**Pull request by brandonbodnar-wk**
Adds support for use_vendor with java code, allowing custom qualified names for the vendored items.

Additionally, addresses (#732) where vendored files were still generated despite being marked vendor and using the use_vendor option.

Pull requests should be made against the 'develop' branch, not master.

@Workiva/messaging-pp @Workiva/product2

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by kevinfrommelt-wf** [comment]
lgtm

**Comment by brianshannan-wf** [comment]
I think you missed a couple cases, it looks like constants from a vendored include referenced in an idl won't be generated with the correct references. You should take a look around [here](https://github.com/brandonbodnar-wk/frugal/blob/9ddef1e6e1519968b2eafc76aa2c9fe8900fc218/compiler/generator/java/generator.go#L314).

A contrived example, but the following should reproduce this

main.frugal
```
include "support.frugal" (vendor)

const i32 reference_vendored_const = support.a_const
```

support.frugal
```
namespace java vendor_namespace.java (vendor="some.vendored.pkg")

const i32 a_const = 1
```

**Comment by brandonbodnar-wk** [comment]
@brianshannan-wf, thanks. I've taken another look at the java compiler code, and see that I had missed the cases for referenced constants, referenced enums, and referenced services. I extended the test cases to include those, and made the required code changes.

**Comment by brianshannan-wf** [comment]
+1

**Comment by kevinfrommelt-wf** [comment]
+1

**Pull request merged**
