### PR TITLE
Initialize ephemeralProperties in NewFContext

### PR DESCRIPTION
**Pull request by yuanmwang-wf**
### Story:
While working on https://jira.atl.workiva.net/browse/INFENG-8048 I noticed this [unit test](https://github.com/Workiva/messaging-sdk/blob/master/lib/go/sdk/iam_test.go#L511) is failing because `ephemeralProperties` is initialized in [Clone](https://github.com/Workiva/frugal/blob/master/lib/go/context.go#L126-L130) but not in [NewFConext](https://github.com/Workiva/frugal/blob/master/lib/go/context.go#L158-L165).   

Workiva-build is failing for a different reason now, should be fixed after https://github.com/Workiva/messaging-docker-images/pull/56 is merged and released. 

### My Test Results:
Same unit test passes now after this change. 

#### Reviewers:
@Workiva/product2

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by yuanmwang-wf** [comment]
Workiva-build is failing for a different reason now, should be fixed after https://github.com/Workiva/messaging-docker-images/pull/56 is merged and released.

**Comment by brianshannan-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
Can you update the skynet.yaml with the new image as well?

**Comment by brianshannan-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
