### PR TITLE
SPLAT-1336 Release v3.14.6

### PR DESCRIPTION
**Pull request by bender-wk**
JIRA: https://jira.atl.workiva.net/browse/SPLAT-1336

@Workiva/product2

* #1599 java-test: bump slf4j-simple from 1.7.30 to 1.7.31 in /test/integration/java/frugal-integration-test
* #1601 java-lib: bump slf4j-simple from 1.7.30 to 1.7.31 in /lib/java
* #1602 java-lib: bump slf4j-api from 1.7.30 to 1.7.31 in /lib/java
* #1604 java-exam: bump slf4j-api from 1.7.30 to 1.7.31 in /examples/java
* #1603 java-exam: bump slf4j-simple from 1.7.30 to 1.7.31 in /examples/java
* #1606 go-exam: bump github.com/apache/thrift from 0.14.1 to 0.14.2 in /examples/go
* #1607 go-lib: bump github.com/apache/thrift from 0.14.1 to 0.14.2 in /lib/go
* #1608 java: Fix spurious IllegalArgumentException with NATS 2.2.0 and no responders
* #1609 java-lib: bump mockito-core from 3.11.1 to 3.11.2 in /lib/java
* #1611 go-tool: bump golang.org/x/tools from 0.1.3 to 0.1.4
* #1612 go-test: bump github.com/apache/thrift from 0.14.1 to 0.14.2 in /test/integration
* #1615 go-exam: bump github.com/rs/cors from 1.7.0 to 1.8.0 in /examples/go
* #1617 java-test: bump jnats from 2.11.4 to 2.11.5 in /test/integration/java/frugal-integration-test
* #1618 java-lib: bump jnats from 2.11.4 to 2.11.5 in /lib/java
* #1620 add workers to fNatsSubscriberTransport

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
<details>
<summary>(1) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>aiohttp < 3.7.4</code> via <code>lib/python/requirements_dev_asyncio.txt</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=frugal">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by houstonking-wf — APPROVED** [review]
QA +1 ; the non-robot PRs have the requisite QA +1s

**Review by danielharasymiw-wf — APPROVED** [review]
+1

**Comment by houstonking-wf** [comment]
@Workiva/release-management-p for merge

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
