### PR TITLE
fix pr to master should fail

### PR DESCRIPTION
**Pull request by blakeroberts-wk**
Same as https://github.com/Workiva/messaging-sdk/pull/659

@Workiva/product2

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.
<details>
<summary>(2) Image validation issues were detected</summary>
<li>Repo does not appear to install package updates in deployable image</li>
<li>Application appears to run using root user.</li>
</details>

## Action Items
* Ensure [package updates](https://wiki.atl.workiva.net/display/SECURITY/Security+Requirements+for+Building+Containers#SecurityRequirementsforBuildingContainers-PackageUpdating) are being installed.
* [Specify a non-root USER](https://wiki.atl.workiva.net/display/SECURITY/Security+Requirements+for+Building+Containers#SecurityRequirementsforBuildingContainers-RunningwithNon-rootUser) in your deploy stage.
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by stevenosborne-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
This is not a big deal, but I just changed the base branch to master, reran workiva build and it passed. Is this expected?

**Comment by brianshannan-wf** [comment]
I think you have to close/open the pull request for workiva build to pick up the change

**Comment by brianshannan-wf** [comment]
@yuanmwang-wf

**Comment by yuanmwang-wf** [comment]
Yay it just failed

**Comment by yuanmwang-wf** [comment]
+10

**Comment by brianshannan-wf** [comment]
+1

**Comment by yuanmwang-wf** [comment]
@Workiva/release-management-p

**Pull request merged**
