### PR TITLE
Golang: Replacing encoding/binary imports with internal.go

### PR DESCRIPTION
**Pull request by natewoods-wf**
Simple improvement to reduce the dependency tree and see what the release cadence of this repository is.

@Workiva/messaging-pp @Workiva/product2

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by brianshannan-wf** [comment]
What is the rationale for doing this? `encoding/binary` is from the standard library, so I don't see the point of replicating it in our code

**Comment by natewoods-wf** [comment]
When using gopherjs on go code, any unnecessary dependencies increase the generated asset size.  This also includes when building go binaries, any dependency adds to the size of the resulting executable. This adds 16 lines of code to replace a dependency that adds more than 825 lines the `encoding/binary` package contains.

Note: this logic can be found in other languages as well: https://github.com/Workiva/frugal/blob/master/lib/dart/lib/src/frugal/internal/headers.dart#L139-L151

**Comment by brianshannan-wf** [comment]
My main concerns with this are:
- -809 lines seems like a very marginal size decrease. It seems like a slippery slope to where size optimization for a general purpose library would stop. Do we replace `encoding/base64`? Do we decide to rewrite `fmt`? Do we stop using third party dependencies all together?
- What do we do if we need additional functions from `encode/binary` in the future? Do we have to find those and copy/paste them into our library as well?
- What are the testing expectations for the code we're moving into our library?

**Comment by natewoods-wf** [comment]
1. These will be addressed in follow up PRs (`fmt`, `gocql` and frugal generated code specifically). Third party dependencies are fine, its just heavy ones are not desired.  Especially when you can get a decrease of 98.06% with no external impact for minimal effort.
2. If we start using a greater subset of `encode/binary` we can always re-evaluate this consolidation and revert if necessary.
3. I was assuming we would trust the original code as tested, but I can add unit tests for this content if desired.

**Comment by brianshannan-wf** [comment]
- I don't think saying we get a 98.06% improvement is really accurate, you'd need to compare the size of everything before and after, not just this single dependency. I don't think replacing fmt is something we want to do, gocql would probably be fine as I think only the generated code needs it for compatibility with the thrift generated code, which we don't need anymore.
- To me, having 809 extra lines, in a general purpose library, is worth not having to make that decision every time we want to do something with that library.

**Comment by natewoods-wf** [comment]
Great Points! I'll close this effort for now.

**Pull request closed without merging**
